"""add_owner_id_to_book

Revision ID: a5584f0f37ee
Revises: adc545dd8c0f
Create Date: 2026-01-21 16:04:26.351152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5584f0f37ee'
down_revision: Union[str, Sequence[str], None] = 'adc545dd8c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'owner_id')
    # ### end Alembic commands ###
